version: 13
port: 5432

default_database:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: postgres
    password: postgres

datasets:
  - name: loyalties
    user: postgres

  - name: payments
    user: postgres

  - name: reservations
    user: postgres

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi